# 실습과제: 당뇨병 데이터 탐색적 분석 연습

병원에서 수집한 당뇨병 예측 데이터를 활용하여 EDA(탐색적 데이터 분석) 기법을 연습해보세요.   
groupby를 활용한 그룹별 분석부터 빈도분석, 교차분석까지 의료 데이터 분석에서 필수적인 기법들을 실습합니다.

## 요구사항

1. **그룹별 분석**
   - 당뇨병 여부별 BMI, 나이의 평균, 표준편차 계산
   - 당뇨병 여부별 BMI 평균 차이 계산

2. **범주형 변수 빈도분석**
   - 성별(Sex) 분포 확인 (빈도와 비율)
   - 교육 수준(Education) 분포 분석  

3. **교차분석 (교차표)**
   - 고혈압과 당뇨병의 연관성 파악
   - 비율 기반 교차표로 패턴 확인

## 힌트

- 그룹별 분석: `df.groupby('그룹컬럼')['타겟컬럼'].agg(['mean', 'std'])`
- 빈도분석: `.value_counts()`, `.value_counts(normalize=True)` 활용
- 교차표: `pd.crosstab(df['컬럼1'], df['컬럼2'])` 사용
- 비율 교차표: `pd.crosstab(df['컬럼1'], df['컬럼2'], normalize='index')`

## 출력 형식
```
정답코드 출력 참고
```

## 실제 의료 데이터 로딩

**BRFSS 2015 당뇨병 데이터셋**을 활용합니다.  
미국 질병통제예방센터(CDC)의 Behavioral Risk Factor Surveillance System에서 수집한 실제 건강 지표 데이터입니다.

In [1]:
# 1. 라이브러리 설치 (최초 1회)
!pip install kagglehub

Requirement already satisfied: kagglehub in /usr/local/lib/python3.12/dist-packages (0.3.13)
Requirement already satisfied: packaging in /usr/local/lib/python3.12/dist-packages (from kagglehub) (25.0)
Requirement already satisfied: pyyaml in /usr/local/lib/python3.12/dist-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in /usr/local/lib/python3.12/dist-packages (from kagglehub) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from kagglehub) (4.67.1)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests->kagglehub) (2025.11.12)

In [2]:
# 2. 데이터 다운로드
import pandas as pd
import kagglehub

# 당뇨병 건강지표 데이터셋 다운로드 (자동으로 최신 버전 받아옴)
path = kagglehub.dataset_download("alexteboul/diabetes-health-indicators-dataset")

print("데이터가 다운로드된 경로:", path)

# 3. 다운로드된 경로에서 파일 불러오기
df = pd.read_csv(f"{path}/diabetes_binary_health_indicators_BRFSS2015.csv")

df.head()

Using Colab cache for faster access to the 'diabetes-health-indicators-dataset' dataset.
데이터가 다운로드된 경로: /kaggle/input/diabetes-health-indicators-dataset

,Diabetes_binary,HighBP,HighChol,CholCheck,BMI,Smoker,Stroke,HeartDiseaseorAttack,PhysActivity,Fruits,...,AnyHealthcare,NoDocbcCost,GenHlth,MentHlth,PhysHlth,DiffWalk,Sex,Age,Education,Income
0,0.0,1.0,1.0,1.0,40.0,1.0,0.0,0.0,0.0,0.0,...,1.0,0.0,5.0,18.0,15.0,1.0,0.0,9.0,4.0,3.0
1,0.0,0.0,0.0,0.0,25.0,1.0,0.0,0.0,1.0,0.0,...,0.0,1.0,3.0,0.0,0.0,0.0,0.0,7.0,6.0,1.0
2,0.0,1.0,1.0,1.0,28.0,0.0,0.0,0.0,0.0,1.0,...,1.0,1.0,5.0,30.0,30.0,1.0,0.0,9.0,4.0,8.0
3,0.0,1.0,0.0,1.0,27.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,0.0,0.0,0.0,0.0,11.0,3.0,6.0
4,0.0,1.0,1.0,1.0,24.0,0.0,0.0,0.0,1.0,1.0,...,1.0,0.0,2.0,3.0,0.0,0.0,0.0,11.0,5.0,4.0

### 기본 데이터 정보 확인

In [3]:
# 기본 데이터 정보 확인
print("=== 데이터 기본 정보 ===")
print(f"데이터 크기: {df.shape}")
print(f"총 환자 수: {df.shape[0]:,}명")
print(f"총 변수 수: {df.shape[1]}개")
print(f"총 컬럼: {df.columns}")

=== 데이터 기본 정보 ===
데이터 크기: (253680, 22)
총 환자 수: 253,680명
총 변수 수: 22개
총 컬럼: Index(['Diabetes_binary', 'HighBP', 'HighChol', 'CholCheck', 'BMI', 'Smoker',
       'Stroke', 'HeartDiseaseorAttack', 'PhysActivity', 'Fruits', 'Veggies',
       'HvyAlcoholConsump', 'AnyHealthcare', 'NoDocbcCost', 'GenHlth',
       'MentHlth', 'PhysHlth', 'DiffWalk', 'Sex', 'Age', 'Education',
       'Income'],
      dtype='object')

## 💻 구현해보세요

In [32]:
import pandas as pd

# 당뇨병 데이터는 df 변수로 로드됨
# 주요 컬럼: Diabetes_binary, BMI, Sex, Education, HighBP, Age 등

# 1. 그룹별 분석
print("=== 1. 그룹별 분석 ===")
# 당뇨병 여부별 BMI, 나이의 평균과 표준편차
diabetes_gb = df.groupby('Diabetes_binary')[['BMI', "Age"]].agg(['mean', 'std'])
diabetes_gb.index = ['정상(0.0)', '당뇨병(1.0)']

print("당뇨병 여부별 BMI, 나이 통계:")
display(round(diabetes_gb, 2))

# 당뇨병 여부별 BMI 평균 차이 계산
bmi_mean_diff = diabetes_gb.iloc[1, 0] - diabetes_gb.iloc[0, 0]
print("\n📊 그룹 간 차이 분석:")
print(f"평균 BMI 차이: {bmi_mean_diff:.2f} (당뇨병 환자가 더 높음)")
print(f"💡 해석: 당뇨병 환자의 평균 BMI가 {bmi_mean_diff:.1f} 높아 비만과 당뇨병의 연관성 시사")

# 2. 범주형 변수 빈도분석
print("\n=== 2. 빈도분석 ===")
# 성별 분포 (빈도와 비율)
sex = df['Sex'].value_counts()

print(f"""성별 분포:
  남성: {sex[0]:,}명 ({(sex[0]/len(df)*100):.1f}%)
  여성: {sex[1]:,}명 ({(sex[1]/len(df)*100):.1f}%)""")

# 교육 수준 분포 분석
edu = df['Education'].value_counts().sort_index()

print(f"\n교육 수준 분포:")
for level, count in edu.items():
    print(f"  수준 {level}: {count:,}명 ({(count/len(df)*100):.1f}%)")

# 3. 교차분석 (교차표)
print("\n=== 3. 교차분석 ===")
# 고혈압과 당뇨병의 연관성 파악
print("\n고혈압 × 당뇨병 교차표 (빈도):")
high_bp_and_diabet = pd.crosstab(df['HighBP'], df['Diabetes_binary'], margins=True)
high_bp_and_diabet.index = ['정상혈압', '고혈압', '전체']
high_bp_and_diabet.columns = ['정상', '당뇨병', '전체']

display(high_bp_and_diabet)

# 비율 기반 교차표로 패턴 확인
print("\n고혈압 × 당뇨병 교차표 (비율):")
high_bp_and_diabet_rate = pd.crosstab(df['HighBP'], df['Diabetes_binary'], normalize='index') * 100
high_bp_and_diabet_rate.index = ['정상혈압', '고혈압']
high_bp_and_diabet_rate.columns = ['정상', '당뇨병']

display(round(high_bp_and_diabet_rate, 1))

=== 1. 그룹별 분석 ===
당뇨병 여부별 BMI, 나이 통계:

            BMI         Age
           mean   std  mean   std
정상(0.0)   27.81  6.29  7.81  3.10
당뇨병(1.0)  31.94  7.36  9.38  2.33

📊 그룹 간 차이 분석:
평균 BMI 차이: 4.14 (당뇨병 환자가 더 높음)
💡 해석: 당뇨병 환자의 평균 BMI가 4.1 높아 비만과 당뇨병의 연관성 시사

=== 2. 빈도분석 ===
성별 분포:
  남성: 141,974명 (56.0%)
  여성: 111,706명 (44.0%)

교육 수준 분포:
  수준 1.0: 174명 (0.1%)
  수준 2.0: 4,043명 (1.6%)
  수준 3.0: 9,478명 (3.7%)
  수준 4.0: 62,750명 (24.7%)
  수준 5.0: 69,910명 (27.6%)
  수준 6.0: 107,325명 (42.3%)

=== 3. 교차분석 ===

고혈압 × 당뇨병 교차표 (빈도):

          정상    당뇨병      전체
정상혈압  136109   8742  144851
고혈압    82225  26604  108829
전체    218334  35346  253680

고혈압 × 당뇨병 교차표 (비율):

        정상   당뇨병
정상혈압  94.0   6.0
고혈압   75.6  24.4

In [ ]:
# @title 정답

import pandas as pd

# 1. 그룹별 분석
print("=== 1. 그룹별 분석 ===")

# 당뇨병 여부별 BMI와 나이의 평균, 표준편차
print("당뇨병 여부별 BMI, 나이 통계:")
diabetes_stats = df.groupby('Diabetes_binary')[['BMI', 'Age']].agg(['mean', 'std'])
diabetes_stats.index = ['정상', '당뇨병']
print(diabetes_stats.round(2))

# 당뇨병 여부별 BMI 평균 차이 계산
bmi_by_diabetes = df.groupby('Diabetes_binary')['BMI'].mean()
mean_diff = bmi_by_diabetes[1] - bmi_by_diabetes[0]  # 당뇨병 환자 - 정상인

print(f"\n📊 그룹 간 차이 분석:")
print(f"평균 BMI 차이: {mean_diff:.2f} (당뇨병 환자가 더 높음)")
print(f"💡 해석: 당뇨병 환자의 평균 BMI가 {mean_diff:.1f} 높아 비만과 당뇨병의 연관성 시사")

# 2. 범주형 변수 빈도분석
print("\n=== 2. 빈도분석 ===")

# 성별 분포 (빈도와 비율)
print("성별 분포:")
sex_counts = df['Sex'].value_counts()
sex_ratio = df['Sex'].value_counts(normalize=True)
for category in sex_counts.index:
    count = sex_counts[category]
    ratio = sex_ratio[category]
    gender = "여성" if category == 1 else "남성"
    print(f"  {gender}: {count:,}명 ({ratio:.1%})")

# 교육 수준 분포
print(f"\n교육 수준 분포:")
edu_counts = df['Education'].value_counts().sort_index()
edu_total = len(df)
for level in edu_counts.index:
    count = edu_counts[level]
    ratio = count / edu_total
    print(f"  수준 {level}: {count:,}명 ({ratio:.1%})")


# 3. 교차분석 (교차표)
print("\n=== 3. 교차분석 ===")

# 고혈압과 당뇨병의 교차표
print(f"\n고혈압 × 당뇨병 교차표 (빈도):")
bp_diabetes_crosstab = pd.crosstab(df['HighBP'], df['Diabetes_binary'], margins=True)
bp_diabetes_crosstab.index = ['정상혈압', '고혈압', '전체']
bp_diabetes_crosstab.columns = ['정상', '당뇨병', '전체']
print(bp_diabetes_crosstab)

# 고혈압과 당뇨병의 비율 교차표
print(f"\n고혈압 × 당뇨병 교차표 (비율):")
bp_diabetes_ratio = pd.crosstab(df['HighBP'], df['Diabetes_binary'], normalize='index')
bp_diabetes_ratio.index = ['정상혈압', '고혈압']
bp_diabetes_ratio.columns = ['정상', '당뇨병']
print((bp_diabetes_ratio * 100).round(1))   # 퍼센트로 표시

=== 1. 그룹별 분석 ===
당뇨병 여부별 BMI, 나이 통계:
       BMI         Age
      mean   std  mean   std
정상   27.81  6.29  7.81  3.10
당뇨병  31.94  7.36  9.38  2.33

📊 그룹 간 차이 분석:
평균 BMI 차이: 4.14 (당뇨병 환자가 더 높음)
💡 해석: 당뇨병 환자의 평균 BMI가 4.1 높아 비만과 당뇨병의 연관성 시사

=== 2. 빈도분석 ===
성별 분포:
  남성: 141,974명 (56.0%)
  여성: 111,706명 (44.0%)

교육 수준 분포:
  수준 1.0: 174명 (0.1%)
  수준 2.0: 4,043명 (1.6%)
  수준 3.0: 9,478명 (3.7%)
  수준 4.0: 62,750명 (24.7%)
  수준 5.0: 69,910명 (27.6%)
  수준 6.0: 107,325명 (42.3%)

=== 3. 교차분석 ===

고혈압 × 당뇨병 교차표 (빈도):
          정상    당뇨병      전체
정상혈압  136109   8742  144851
고혈압    82225  26604  108829
전체    218334  35346  253680

고혈압 × 당뇨병 교차표 (비율):
        정상   당뇨병
정상혈압  94.0   6.0
고혈압   75.6  24.4